### ISSUE TITLE
[Pathway Issue]: WP4629 - Oxygen transporter in pathway

### ISSUE THREAD

**Issue by aish181095** [wikipathways/wikipathways-help#103]
### What is the issue with the pathway?

There is a OXYT , which I guess is the oxygen transporter in this pathway. Looking at the pathway, this looks like the diffusion of oxygen across the cell which does not require a transporter. Or is this some energy-dependent transporter in this pathway?

![image](https://github.com/wikipathways/wikipathways-help/assets/37527519/94319598-93d1-4ceb-8ebc-f2661ef695ee)

### What kind of content issue is this?

- [ ] Missing content
- [X] Incorrect content
- [ ] Duplicated content
- [ ] Other

### Type of revision

- [ ] Major
- [X] Minor
- [ ] Deletion

**Comment by khanspers** [comment]
I think you are right that oxygen moves freely over the plasma membrane via diffusion. I will point the original author to this discussion.

**Comment by khanspers** [comment]
The original author of WP4629 has indicated that the OXYT node was added to the pathway to make it useful for a computer model. So the pathway can be updated to remove the OXYT node. Additional improvements include updating the dead link to WP4628 in the description.
