### ISSUE TITLE
Ask for upload rights PathVisio

### ISSUE THREAD

**Issue by TomPauly** [wikipathways/wikipathways-help#12]
Currently I am working in PathVisio and I would like to upload my pathway. However I got a notification that I don't have the rights for uploading, see picture below. Therefore I would like to ask for these rights.

Greetings,
Tom

![image](https://user-images.githubusercontent.com/113432534/205928370-fa149e8a-219e-4ce5-9772-3f1ef8c6ce18.png)

**Comment by khanspers** [comment]
Hi Tom,
I found your WikiPathways account (TomPauly) and updated your account permissions to allow for upload via PathVisio. Let me know if you have any additional questions.

Kristina
