### ISSUE TITLE
error getting gmt data

### ISSUE THREAD

**Issue by jd690764** [wikipathways/wikipathways-help#132]
Hi,

I am trying to use clusterProfiler::enrichWP that points to this url:

"https://wikipathways-data.wmcloud.org/current/gmt/

It seems the latest update has had some issues - most of the organisms are missing. Can you please take a look?

Thanks,
Janos

**Comment by khanspers** [comment]
Hi @jd690764, I think you are using an older version of clusterProfiler. The correct url is https://data.wikipathways.org/current/gmt/, which is in the latest version.

**Comment by jd690764** [comment]
Hi Kristina,

I think my version (v4.10.1) was up-to-date with R (v4.3.0) and Bioc
(v3.18). I updated everything to the latest and it works fine now.

Thank you,
Janos

**Comment by khanspers** [comment]
Great thank you!
