### ISSUE TITLE
WP1382 not accessible on the current website

### ISSUE THREAD

**Issue by need47** [wikipathways/wikipathways-help#137]
I'm wondering why some pathways are not accessible on the present website, though they are accessible on the classic site. e.g.,

(OK) https://classic.wikipathways.org/index.php/Pathway:WP1382
(404) https://www.wikipathways.org/index.php/Pathway:WP1382

Usually the second link will be redirected to the following current url:

```
https://www.wikipathways.org/index.php/Pathway:WP1
->
https://www.wikipathways.org/pathways/WP1.html (preferred)
```

**Comment by khanspers** [comment]
Hi @need47, our official website (https://www.wikipathways.org/) contains only pathways that have been reviewed and approved to meet our [content requirements](https://www.wikipathways.org/contribute.html#content_requirements). New pathways that are not yet reviewed/approved,  pathways under construction, and pathways that don't meet these criteria will only be available on the classic site (https://classic.wikipathways.org/index.php/WikiPathways).

On the classic pathway page, the Quality Tags will have information about potential content issues. For approved pathways, you would also see the Approved quality tag.

**Comment by need47** [comment]
I see, thanks a lot.
