### ISSUE TITLE
Only first three lines of description available

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#14]
It seems that only the first three lines of description are visible, e.g., here: https://www.wikipathways.org/pathways/WP4233.html
The fourth line can still be selected, and I can copy paste the text that is there. But maybe it is hidden under the pathway figure? At some point we had a button to show more text, but I don't see this any more

**Comment by egonw** [comment]
@danidi, can you confirm it works again?

**Comment by danidi** [comment]
Yes, the more text button is back and works as expected.
