### ISSUE TITLE
I don't find my pathways on the new site

### ISSUE THREAD

**Issue by docmattc** [wikipathways/wikipathways-help#15]
Pathways I've created (eg WP5277, WP5276, WP5279, WP5280, WP5324) don't seem to be on the new site

**Comment by egonw** [comment]
I was about to write: "@docmattc, that is likely because they have not been approved."

But https://classic.wikipathways.org/instance/WP5277 has been approved a long time ago...

**Comment by danidi** [comment]
WP5779 doesn't exist on the old page either, is there a typo with the number?
WP5324 is still under construction, so here it is not showing because it has not been approved. 
For the rest, could the order of the approved tag matter? They all have the lipid maps tag befor the approved tag.

**Comment by docmattc** [comment]
WP5772 -> WP5279

**Comment by egonw** [comment]
Checking the website database:

* https://github.com/wikipathways/wikipathways-database/tree/main/pathways/WP5277 is missing but https://classic.wikipathways.org/instance/WP5277 is approved
* https://github.com/wikipathways/wikipathways-database/tree/main/pathways/WP5276 is missing but https://classic.wikipathways.org/instance/WP5276 is approved
* https://github.com/wikipathways/wikipathways-database/tree/main/pathways/WP5279 is missing but https://classic.wikipathways.org/instance/WP5279 is approved
* https://github.com/wikipathways/wikipathways-database/tree/main/pathways/WP5280 is missing but https://classic.wikipathways.org/instance/WP5280 is approved
* https://github.com/wikipathways/wikipathways-database/tree/main/pathways/WP5324 is under construction

**Comment by danidi** [comment]
Ok, WP5279 has the approved tag first, so that can't be the issue.

**Comment by fehrhart** [comment]
Same here, I am missing about 40 pathways from the rare disease community. The new page has 83, the old rare disease community tag was for about 120 pathway. 
Example of missing pathways:
https://classic.wikipathways.org/index.php/Pathway:WP5223 
https://classic.wikipathways.org/index.php/Pathway:WP5224
https://classic.wikipathways.org/index.php/Pathway:WP5221
https://classic.wikipathways.org/index.php/Pathway:WP5222

All approved :)

**Comment by larsgw** [comment]
The daily GPML sync only seems to act on pathways that have been changed in the last 24 hours: 

```java
WSPathwayInfo [] changedPwy = client.getRecentChanges(new SimpleDateFormat("yyyyMMddhhmmss").parse(args[0]));
```

https://github.com/wikipathways/gpml-sync-action/blob/b514398629f9a429762a2038b84d3004de3f8b6b/src/org/wikipathways/SyncAction.java#L30

If these pathways were approved after the last manual sync (I'm having trouble finding when that was) they would not be picked up by the automatic sync.

> Example of missing pathways:
> https://classic.wikipathways.org/index.php/Pathway:WP5223
> https://classic.wikipathways.org/index.php/Pathway:WP5224
> https://classic.wikipathways.org/index.php/Pathway:WP5221
> https://classic.wikipathways.org/index.php/Pathway:WP5222

These do seem to be available now: https://www.wikipathways.org/pathways/WP5221.html, https://www.wikipathways.org/pathways/WP5222.html, etc.

**Comment by danidi** [comment]
I think there are two different issues here: the rare disease pathways are missing from the list here: https://www.wikipathways.org/communities/rarediseases.html. While https://classic.wikipathways.org/index.php/Pathway:WP5224 has the rare disease tag, the corresponding pathway from the new site https://www.wikipathways.org/pathways/WP5224.html does not have any communities connected. 
Some of the lipid maps pathways are however completely missing.

**Comment by egonw** [comment]
> the rare disease pathways are missing from the list here

Pathways have to be added by hand to communities. I don't think we automated that yet. @danidi, that's a separate issue. This can be done as explained on this page: https://www.wikipathways.org/help_communities.html

But tl;dr, edits the `txt` files in this folder: https://github.com/wikipathways/wikipathways-database/tree/main/communities

**Comment by egonw** [comment]
> The daily GPML sync only seems to act on pathways that have been changed in the last 24 hours

Okay, then we just need to add them by hand.

**Comment by AlexanderPico** [comment]
That's correct: the sync action only checks for recent changes or new pathways in past 24 hours. 

* Community tag changes should be made on the new site (tags on the classic site are ignored)
* Removal of approval tag (rare) need to be handled manually (delete the GPML from wikipathways-database)
* Addition of approval tag:
    A. On a recently changed pathway in the past 24 hours: automatically handled (no action required)
    B. On a "stale" pathway: missed! (add WP folder and GPML to wikipathways-database)

@fehrhart If you have a long list of WPIDs that should be added, I can run the local script easily and do them as a batch. Just provide me with the list of WPIDs.

**Comment by AlexanderPico** [comment]
Ok. I updated the SyncAction.jar to also sync any approved pathway not previously processed, regardless of it having been recently changed. So, this will now catch case B above.

I just ran it now and it added:

- WP5077
- WP5120
- WP5188
- WP5195
- WP5235
- WP5265
- WP5276
- WP5277
- WP5279
- WP5280
- WP5287
- WP5302

@docmattc That added 5 more new pathway to [your list](https://www.wikipathways.org/authors/Conroy%20lipids.html) :) 

If anyone can find additional approved WPIDs that are not on the new site, please reopen and list examples.

Thanks for catching this!
