### ISSUE TITLE
Minor graphical issue on website

### ISSUE THREAD

**Issue by fehrhart** [wikipathways/wikipathways-help#18]
When decreasing window size the "Go to..." moves under the "welcome to the new..." box. See screenshot
![image](https://user-images.githubusercontent.com/11389574/219011018-fc24529a-fe0f-4f67-b4cd-339b8fe4061d.png)

(happens for both, Firefox and Chrome - other browsers not tested)

**Comment by larsgw** [comment]
The browse section also breaks a bit.

![Screenshot_20230215_121005](https://user-images.githubusercontent.com/14018963/219011579-59842793-8f8d-4921-9b43-aee1b6ce1ead.png)

**Comment by AlexanderPico** [comment]
Fixed!

The site isn't perfectly reactive for all formats (e.g., mobile). It is much much more usable than the old site though. Mobile hasn't been a requirement or major use case. I've spent more time than I'd like to admit trying to get those front page features to react well to all sizes :)
