### ISSUE TITLE
additional / in link of search result (forwarding from new.wikipathways)

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#20]
When performing the search, I see the correct links (although still pointing to new) in the search result list. But when I click on the result, I end up on a page such as "https://www.wikipathways.org//pathways/WP481.html" with two / symbols. The link still works fine.
I see the same, if I use https://new.wikipathways.org/pathways/WP481.html directly. So maybe there is an additional / in the redirect information?

**Comment by AlexanderPico** [comment]
Yep, but it doesn't hurt anything. Duplicate path `/` characters are treated as singular by HTTP
