### ISSUE TITLE
Weird characters in title issue?

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#21]
https://www.wikipathways.org/pathways/WP3634.html shows two curation issues. 
One is: 
weirdCharacterTitles: .x we found 1 problem(s):  [Titles with unexpected characters (only allow alphanumerics and spaces):1](https://www.wikipathways.org/wikipathways-collection/reports/WP3634.html#fda87b3f)

I don't see anything weird in the title or even the names of the data nodes. Are brackets () considered weird in a title?

**Comment by egonw** [comment]
> Are brackets () considered weird in a title?

Yeah, that was the decision at some point. Evaluations of acceptable titles and their characters would be a good topic for the curator meeting. I will update the test accordingly.

**Comment by danidi** [comment]
Thanks, I will bring the topic up there.

**Comment by khanspers** [comment]
It would be great to know what the list of allowed characters are (the test indicates alphanumeric and space), for example is a dash (-) allowed?

**Comment by egonw** [comment]
> It would be great to know what the list of allowed characters are (the test indicates alphanumeric and space), for example is a dash (-) allowed?

The original list (decided during a WP telcon) we created was not satisfactory: it resulted in flagged titles that were also okay. I am still waiting for a new list and do not have a good list of what is okay and what is not.

**Comment by khanspers** [comment]
I found a list from a 2021 meeting: [WP conf call 2021-03-03](https://docs.google.com/document/d/1p0e2w7S3sA8IXezA2QRa9B0hg8eehkIQYI1Ff6-qeMM/edit#bookmark=id.5qqbto80eg9l)

Highlights of notes:
- Allowed characters: brackets/parentheses, hyphens, period/decimal, forward slash
- Broad only allows alphanumeric and space

Added this topic to next [Curators meeting](https://docs.google.com/document/d/1nMjmD7wKo1Km2Xv0Lunv6SOy1k6ktL-PohKSLTdrEpE/edit?usp=sharing).

**Comment by egonw** [comment]
Does the below sound right? I also had the colon which seems used several times.

```java
if (Character.isAlphabetic(c)) {}
  else if (Character.isDigit(c)) {}
  else if (Character.isSpaceChar(c)) {}
  else if (c == '-') {}
  else if (c == '.') {}
  else if (c == ',') {}
  else if (c == ':') {}
  else if (c == '(') {}
  else if (c == ')') {}
  else if (c == '[') {}
  else if (c == ']') {}
  else if (c == '/') {}
  else {
    weirdCharCount++;
  }
```

**Comment by egonw** [comment]
@khanspers, perhaps we should add the `'` (single quote) too? See https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation%20-%20Daily%20All/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/General/weirdCharacterTitles/

With this report:

```
Titles with unexpected characters (only allow alphanumerics and spaces):6. Details:
http://classic.wikipathways.org/instance/WP2632_r107272 'Superpathway of pyridoxal 5'-phosphate biosynthesis and salvage' has 1 weird characters
http://classic.wikipathways.org/instance/WP2953_r118319 'Pyridoxal 5'-phosphate biosynthesis' has 1 weird characters
http://classic.wikipathways.org/instance/WP2631_r107271 'Superpathway of pyridoxal 5'-phosphate biosynthesis and salvage' has 1 weird characters
http://classic.wikipathways.org/instance/WP2955_r87623 'Pyridoxal 5'-phosphate Salvage Pathway' has 1 weird characters
http://classic.wikipathways.org/instance/WP2371_r126375 'Parkinson's disease pathway' has 1 weird characters
http://classic.wikipathways.org/instance/WP2059_r119468 'Alzheimer's disease and miRNA effects' has 1 weird characters
 ==> expected: <0> but was: <6>
```

**Comment by khanspers** [comment]
Yes, that seems reasonable. I have added an [FAQ item](https://github.com/wikipathways/wikipathways-faq/discussions/24) about this for now.

**Comment by egonw** [comment]
Okay, three fails left:

```
http://classic.wikipathways.org/instance/WP3644_r118983 'NAD+ metabolism' has 1 weird characters
http://classic.wikipathways.org/instance/WP3645_r123910 'NAD+ biosynthetic pathways' has 1 weird characters
http://classic.wikipathways.org/instance/WP4210_r123510 'Tryptophan catabolism leading to NAD+ production' has 1 weird characters
```

Now, people have indicated in the past to not like acronyms in titles either, so the it's not immediately obvious to me if we should add the `+` to the allowed characters. What do you think?

**Comment by Chris-Evelo** [comment]
The + is indeed commonly used for NAD+ (the oxidized form of Nicotinamide adenine dinucleotide). Even though people tend to forget about charges for most other things. That is probably because the reduced form liberates a proton and is normally written as NADH/H+. The abbreviation itself is very common and almost as well known as ATP or DNA so I would not worry about that. The problem is of course that while I would be fine with people using NAD+ in titles that might not be trie for other uses of the +.

**Comment by mkutmon** [comment]
I somehow missed this issue discussion. Partially those guidelines also came from MSigDb for the GMT files. I will check if I find the comments they made. The most important for them was that there shouldn't be two pathways with the same name within one species. @egonw Do we already have a test for that? :)

**Comment by mkutmon** [comment]
MSigDB only wants alphanumeric characters and underscores. I think the script now replaces all special characters (in case they exist) with underscores. Erik also needed to make changes to the titles for some tool integration, right? Do we know their guidelines? 
@AlexanderPico we might need to check the new generation of the GMT file (with Github action) if we need to make any changes to the titles to make sure downstream analyses work fine.

**Comment by AlexanderPico** [comment]
Looks like it replaces _ and + in titles with blanks.  Anything to add or change?
https://github.com/wikipathways/wikipathways-data-release/blob/main/make-gmts.R#L23

**Comment by AlexanderPico** [comment]
I see parens, hyphens and plus signs in GMT pathway titles.  I'll look into updating the GMT script...

**Comment by AlexanderPico** [comment]
@mkutmon Done! All non-alphanumerics in titles in GMTs are replaced by an underscore.
https://github.com/wikipathways/wikipathways-data-release/commit/0011d915cf8b67f18328d5b1efdc6cb2cd2b32f7
