### ISSUE TITLE
Pathway search does not recognise some search keywords which are in pathway titles

### ISSUE THREAD

**Issue by fehrhart** [wikipathways/wikipathways-help#22]
I was concretely searching for terms like:
"22q11.2" or "3q29" -> those pathways are in the new website, in the rare disease community but I get "no result" in the search
"distal" -> gives me 4 pathways as a result, but not https://www.wikipathways.org/pathways/WP4950.html "16p11.2 distal deletion syndrome"

**Comment by egonw** [comment]
I can confirm the observation. It seems that WP4950 is not indexed (yet). @AlexanderPico, what does the Google dashboard say about how much is indexed now?

**Comment by AlexanderPico** [comment]
We lost a lot of previously indexed content when switching from "new" to "www". Approximately half the pathways are indexed today. That number was much higher before the switch and should start going up soon after our legitimate redirects are reviewed.

**Comment by AlexanderPico** [comment]
It's probably not worth anyone's time to test search until the reindexing is complete?

**Comment by khanspers** [comment]
Both of these queries work now after Alex implemented a new search tool. Here's one of them: https://www.wikipathways.org/search.html?query=22q11.2.
