### ISSUE TITLE
A section/chapter on the coverage through the semantic web is missing.

### ISSUE THREAD

**Issue by andrawaag** [wikipathways/wikipathways-help#23]
On the new website, it is unclear how Wikipathways is linked to the semantic web [1].

[1] https://yummydata.org/endpoint/18?date=2023-03-01

**Comment by egonw** [comment]
@andrawaag, I am going to need some more input. Do you mean that https://www.wikipathways.org/rdf.html should be easier to reach from the homepage?

**Comment by andrawaag** [comment]
Both and maybe a [Fair Data Point](https://www.fairdatapoint.org/) listed on the main page. Now the RDF work is not visible when entering the main page.

**Comment by egonw** [comment]
How do you expect it to be mentioned? The SPARQL endpoint is mentioned on the front page:

![image](https://user-images.githubusercontent.com/26721/222671968-2206abe8-6c23-45c9-86a7-0b6c9441c046.png)

And the RDF is listed on the Download page:

![image](https://user-images.githubusercontent.com/26721/222672052-5af32d9e-78a5-46b2-8d68-b4eaf4f3f529.png)

Restoring the FDP would be nice, and I think EJPRD was looking into that. @fehrhart, do you remember?

**Comment by egonw** [comment]
Please explain what you expect.

**Comment by andrawaag** [comment]
SPARQL points to the endpoint which indeed is a mentioning.
