### ISSUE TITLE
bad gateway / data unavailable

### ISSUE THREAD

**Issue by AMChalkie** [wikipathways/wikipathways-help#24]
Hi,
Looks like something is off. Is there an alternative landing page for things?

Best wishes
Alistair

https://wikipathways-data.wmcloud.org/
502 Bad Gateway
nginx/1.18.0

**Comment by khanspers** [comment]
Hi @AMChalkie, the wikipathways data page is back up.

**Comment by AMChalkie** [comment]
Excellent, thanks.
