### ISSUE TITLE
Forum or contact discussion page?

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#3]
At the bottom of the page, the link to "Forum" links to https://github.com/wikipathways/wikipathways-help/discussions, which I thought was more a read-only FAQ page. 
The "About" page and the "contact us" in the curate section links to https://github.com/wikipathways/wikipathways.github.io/discussions, which looks quite empty at the moment, but I think was more meant as public forum to discuss. 
I think the Forum link should also link to the second one as well, but maybe we would also need a more prominent link to the FAQ (I only found it at the bottom of the help page). Or we want to combine the two places, as it might be confusing for users which of the discussion boards is actually in use.

**Comment by khanspers** [comment]
- FAQ is now here: https://github.com/wikipathways/wikipathways-faq/discussions
- New repo for Discussions (forum) and reporting issues is: https://github.com/wikipathways/wikipathways-help
- All issues from https://github.com/wikipathways/wikipathways.github.io/issues have been transferred to https://github.com/wikipathways/wikipathways-help/issues
- links have been updated

**Comment by khanspers** [comment]
updated the footer to include FAQ and updated some links in Terms of Use and Contribute pages.
