### ISSUE TITLE
WP5123 description missing on new page

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#37]
https://www.wikipathways.org/pathways/WP5123.html shows "test" as description, but there is a description available on the classic page: https://classic.wikipathways.org/index.php?title=Pathway:WP5123

**Comment by khanspers** [comment]
That's odd. I just made some updates to the description at classic, which should trigger an update of the pathway at WP. Will check back tomorrow.

**Comment by khanspers** [comment]
Just realized the gpml had two entries for "wikipathways-description". Removed the erroneous one (test) on classic, which should now trigger an update.

**Comment by khanspers** [comment]
The description is now displaying correctly (https://www.wikipathways.org/pathways/WP5123.html). Closing.
