### ISSUE TITLE
Linkout to InterPro not working correctly

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#39]
At least on the classic page, the linkouts to InterPro give a 404 error, e.g. http://www.ebi.ac.uk/interpro/displayiproentry/?ac=IPR008366 
A working link would be for example http://www.ebi.ac.uk/interpro/entry/InterPro/IPR008366/.

**Comment by khanspers** [comment]
Is this true for the new Jekyll site too? I can't find a pathway with an Interpro identifier to check.

**Comment by danidi** [comment]
An example is AGC here https://classic.wikipathways.org/index.php/Pathway:WP5373. I realized now that it works fine on the new page https://www.wikipathways.org/pathways/WP5373. So it is probably not necessary to change this.

**Comment by khanspers** [comment]
OK, since it works on the new site I'm closing this.
