### ISSUE TITLE
Pathway curation report - at least 15 metabolites

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#5]
The "at least 15 metabolites" test fails with the comment of "Unexpectedly low number of metabolites: 37". From the name I would think that it should fail if it is below 15. But if 15 is the threshold, why is 37 (or 51 in the second example) low? 
https://new.wikipathways.org/wikipathways-collection/reports/WP4792.html
https://new.wikipathways.org/wikipathways-collection/reports/WP4545.html

**Comment by egonw** [comment]
I believe I found the problem. Not where I was expecting it :/

**Comment by egonw** [comment]
Thanks. Confirmed, fixed, and updated validation results being uploaded to the website. @danidi, thanks for pinging me!
