### ISSUE TITLE
SPARQL page error

### ISSUE THREAD

**Issue by allenbaron** [wikipathways/wikipathways-help#69]
SPARQL queries at https://sparql.wikipathways.org/ are currently returning the error:

>502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by marvinm2** [comment]
Hello,
Thank you for informing us. I restarted the service yesterday afternoon and it should be functional again.

**Comment by allenbaron** [comment]
Thanks!

_Hopefully I wasn't responsible for it going down._ :sweat_smile:
