### ISSUE TITLE
Missing description on wikipathways development readme

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#7]
The "Code" link points to https://github.com/wikipathways/wikipathways-development. There are some introductory questions there (e.g. What is Wikipathways?, Overview of the different components of the project,...), but no anwers so far.

**Comment by khanspers** [comment]
The GitHub logo/link replaced the old Code link, and now goes to https://github.com/wikipathways. Alex just added a nice ReadMe with links to relevant repos. Closing this.
