### ISSUE TITLE
Adding ontology tag not possible on classic site

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#75]
As mentioned here https://github.com/wikipathways/wikipathways-help/discussions/68, it is currently not possible to find a new ontology tag for a pathway. Both the search and the tree don't show any results.

**Comment by khanspers** [comment]
For me, both the search and tree works: 
<img width="439" alt="Screen Shot 2023-10-19 at 1 45 30 PM" src="https://github.com/wikipathways/wikipathways-help/assets/1442197/0b54b422-2f1e-42fd-a892-595b90a142bc">
<img width="421" alt="Screen Shot 2023-10-19 at 1 44 30 PM" src="https://github.com/wikipathways/wikipathways-help/assets/1442197/749f4c29-2797-4217-969d-bdeea23a5cc1">

**Comment by alexmadsen1** [comment]
seems to be working now.

**Comment by danidi** [comment]
Yes, works fine for me as well. Seems to have been a temporary issue only
