### ISSUE TITLE
[Pathway Issue]: Invalid IRI value (space)

### ISSUE THREAD

**Issue by svandenhoek** [wikipathways/wikipathways-help#76]
### Issue

The dataset (as downloaded from https://data.wikipathways.org/current/rdf/) contains invalid IRIs:
* GraphDB (importing files) -> `org.eclipse.rdf4j.sail.SailException: Invalid IRI value`
* Apache Jena (`riot --validate`) -> `Bad character in IRI (space)`

The issue seems to be that several author IRIs contain a space, which is not allowed (`<http://rdf.wikipathways.org/User/firstname lastname>`).

The following query should show the IRIs causing issues (through https://sparql.wikipathways.org/):
```sparql
SELECT * WHERE {
 ?p rdf:type foaf:Person .
 FILTER( CONTAINS(STR(?p), " ") )
}
```

### Suggested solution
Replace the space with a valid IRI character. `%20` might work but perhaps something like a underscore or dot is more readable (hyphen could also work but might cause readability issues with certain names).

### Further reading
* https://afs.github.io/rdf-iri-syntax.html#notes-iris
* https://www.w3.org/TR/turtle/#sec-escapes (the note)
* https://datatracker.ietf.org/doc/html/rfc3987

### What kind of content issue is this?

- [ ] Missing content
- [X] Incorrect content
- [ ] Duplicated content
- [ ] Other

### Type of revision

- [ ] Major
- [ ] Minor
- [ ] Deletion

**Comment by khanspers** [comment]
@egonw @marvinm2 @AlexanderPico

**Comment by svandenhoek** [comment]
Any update on this yet?

**Comment by svandenhoek** [comment]
That's understandable. Interesting to hear the tool that is used to generate the RDF also says it's invalid. Perhaps a difference in used version or RIOT being more strict than Jena in general?
```
$ riot --version
Apache Jena RIOT version 4.9.0
```

The issue occurs in multiple IRIs (the SPARQL query in my first message should be able to show which ones are invalid using your SPARQL endpoint). You can find the full output of `riot --validate **/*.ttl &> out_and_err.log` [here](https://github.com/wikipathways/wikipathways-help/files/13278204/out_and_err.log), but to give a snippet of this:
```txt
[...]
10:21:51 INFO  riot            :: File: authors/WP10.ttl
10:21:51 ERROR riot            :: [line: 9, col: 168] Bad character in IRI (space): <http://rdf.wikipathways.org/User/Christine[space]...>
[...]
10:21:51 INFO  riot            :: File: authors/WP1008.ttl
10:21:51 ERROR riot            :: [line: 9, col: 162] Bad character in IRI (space): <http://rdf.wikipathways.org/User/Mick[space]...>
[...]
10:21:51 INFO  riot            :: File: authors/WP1014.ttl
10:21:51 ERROR riot            :: [line: 9, col: 126] Bad character in IRI (space): <http://rdf.wikipathways.org/User/Christine[space]...>
[...]
10:21:51 INFO  riot            :: File: authors/WP113.ttl
10:21:51 ERROR riot            :: [line: 9, col: 198] Bad character in IRI (space): <http://rdf.wikipathways.org/User/L[space]...>
[...]
```

**Comment by egonw** [comment]
> Interesting to hear the tool that is used to generate the RDF also says it's invalid

No, I meant that Apache Jena does not complain. But I now see the problem. It is not 'my' RDF that is the problem, but the author triples. Can you confirm these files are from the `authors.zip` file? cc @AlexanderPico

**Comment by svandenhoek** [comment]
I meant it as in that riot is one of the command-line tools part of Apache Jena, so one would assume that the the different parts of Apache Jena would not have different levels of strictness.

And yes, it's indeed the `authors.zip`.

**Comment by egonw** [comment]
@marvinm2, heads up for loading the Nov 2013 RDF release in a few days

**Comment by egonw** [comment]
@svandenhoek, thanks for the report. I just pushed a fix: https://github.com/wikipathways/wikipathways-data-release/commit/6653c22fc9fef1386145f03b7c92266bbd118026

That won't fix the file in the October release, but it will fix it for the release tomorrow.

**Comment by egonw** [comment]
I validating the Nov 2023 authors.zip and it seems to no longer give the problem.

**Comment by svandenhoek** [comment]
Appreciate the fix! The `authors.zip` indeed loaded into GraphDB without any issues.
