### ISSUE TITLE
Image on new homepage shows incorrect gene

### ISSUE THREAD

**Issue by eweitz** [wikipathways/wikipathways-help#97]
In https://www.wikipathways.org, the first big animation shows that clicking on "ACE" brings up a Scholia page for "ACE2".  

As seen in [WP554](https://www.wikipathways.org/pathways/WP554.html), the Scholia page should be for ACE, not ACE2.  That issue aside, the animation nicely demonstrates new WikiPathways interactive features!

Here's a screenshot showing the problem:

<img width="1440" alt="ACE2_shown_for_click_on_ACE_Wikipathways_homepage__2024-01-17" src="https://github.com/wikipathways/wikipathways-help/assets/1334561/955c809c-94d7-41e9-8d6d-efcef9b4e01c">

**Comment by khanspers** [comment]
Thanks for catching that @eweitz. We will update it as soon as possible.

**Comment by AlexanderPico** [comment]
It was indeed just a demo of the functionality that I made by hand before the site was done. So it's not "real".  We are going to switch away from Scholia soon and will update it then. Thanks!
